// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:karee_inject/src/annotations/controller.dart' as prefix0;
import 'routes_test.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ControllerReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'MyController',
            r'.MyController',
            7,
            0,
            const prefix0.ControllerReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.MyController() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 2,
              r'toString': 1,
              r'noSuchMethod': 2,
              r'hashCode': 1,
              r'runtimeType': 1,
              r'add': 0,
              r'addAsync': 0,
              r'myService': 1,
              r'myService=': 2
            })
      ],
      null,
      null,
      <Type>[prefix1.MyController],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'add': (dynamic instance) => instance.add,
        r'addAsync': (dynamic instance) => instance.addAsync,
        r'myService': (dynamic instance) => instance.myService
      },
      {r'myService=': (dynamic instance, value) => instance.myService = value},
      null,
      [
        const [2, 0, null],
        const [0, 0, null],
        const [1, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
