import '../extensions_services.dart';
import '/app/controllers/dashboard/dash_board_controller.dart';

/// Generated by Karee

extension DashBoardControllerExtension on DashBoardController {
  static late final DashBoardController? service;
  static bool loaded = false;
  void init() {
    DashBoardControllerExtension.service = this;
    DashBoardControllerExtension.loaded = true;
    userService = serviceExtensions['UserService']();
  }

  DashBoardController get self {
    init();
    return this;
  }
}

DashBoardController get $extendedDashBoardController {
  if (!DashBoardControllerExtension.loaded) {
    DashBoardController().self;
  }
  return DashBoardControllerExtension.service!;
}
