import 'package:example/app/controllers/settings/settings_controller.dart';

/// Generated by Karee 

extension SettingsControllerExtension on SettingsController {
	static late final SettingsController? service;
	static bool loaded = false;
	void init(){
		SettingsControllerExtension.service = this;
		SettingsControllerExtension.loaded = true;
	}
	SettingsController get self {
		init();
		return this;
	}
}

SettingsController get $extendedSettingsController {
	if(!SettingsControllerExtension.loaded){
		SettingsController().self;
	}	return SettingsControllerExtension.service!;
}